### ISSUE TITLE
Bug pm5

### ISSUE THREAD

**Issue by NdaruAjaa** [poggit-orphanage/PlayerSelectors#5]
The tag selector doesn't work
Example: @a @r @p @s

**Comment by jasonw4331** [comment]
Can you provide more details? It works for me.

**Comment by NdaruAjaa** [comment]
> 

![Screenshot_2023-07-19-10-27-54-669-edit_com mojang minecraftpe](https://github.com/poggit-orphanage/PlayerSelectors/assets/120300909/8deed177-ada7-49a7-adf0-972ea22ac3c0)
@a @s @r @p can not be used

**Comment by jasonw4331** [comment]
This plugin only operates on commands. That isn't even listed as a feature of this...
